theme: minima 

plugins:
  - jekyll-pdf-embed

header_pages:
  - about.md
  - research.md 
  - cv.md
  - publications.md


twitter_username: yanjus4christ
linkedin_username: samueladeyanju
email: samuel.adeyanju@ubc.ca


