theme: minima 


header_pages:
  - about.md
  - research.md 
  - cv.md
  - publications.md


twitter_username: yanjus4christ
linkedin_username: samueladeyanju
email: adesam1@student.ubc.ca


plugins: ['jekyll-twitter-plugin']
